services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: pms-backend-dev
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - HOST=0.0.0.0
      - ALLOWED_ORIGINS=http://localhost:3002,http://pms-frontend-dev:3002,http://127.0.0.1:3002
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - pms-network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: pms-frontend-dev
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - FRONTEND_PORT=3002
      - VITE_API_URL=http://localhost:3001
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - pms-network

networks:
  pms-network:
    driver: bridge
