version: '3.8'

services:
  backend:
    build: ./backend
    container_name: pms-backend
    hostname: pms-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - JWT_SECRET=your_secure_jwt_secret_key_here
      - BACKEND_PORT=3001
      - ALLOWED_ORIGINS=http://localhost:3002,http://pms-frontend:3002
    restart: unless-stopped
    networks:
      - pms-network
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /app/dist
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').request({port: 3001, path: '/health'}, (res) => process.exit(res.statusCode === 200 ? 0 : 1)).end()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build: ./frontend
    container_name: pms-frontend
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - FRONTEND_PORT=3002
      - VITE_API_URL=/api
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - pms-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3002"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  pms-network:
    driver: bridge
    name: pms-network
