version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: pms-backend-dev
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run start:dev
    restart: unless-stopped
    networks:
      - pms-network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: pms-frontend-dev
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - FRONTEND_PORT=3002
      - VITE_API_URL=http://localhost:3001
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - pms-network

networks:
  pms-network:
    driver: bridge
